name: "bazel"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # The CACHE_ID is 1 if the run happens on the main branch or the pull request was newly opened.
  # Otherwise, the ID corresponds to the pull request ID.
  # We have to use this boolean syntax because Github actions do not support ternary expressions.
  CACHE_ID: ${{ github.event_name == 'pull_request' && (github.event.action != 'opened' && github.event.pull_request.number) && '' }}

# Cancel any preceding run on the pull request.
concurrency:
  group: bazel-${{ env.CACHE_ID }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build_direct:  # Build p4c directly.
    runs-on: ubuntu-latest
    env:
      BAZEL: bazelisk-linux-amd64
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: "~/.cache/bazel"
        # Create cash entry for every run (by using unique key derived from commit hash).
        # See https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
        key: ${{ runner.os }}-${{ env.CACHE_ID }}-bazel-build-direct
        restore-keys: |
          ${{ runner.os }}-${{ env.CACHE_ID }}-bazel-build-direct

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.1/$BAZEL"
        chmod +x $BAZEL
        sudo mv $BAZEL /usr/local/bin/bazel

    - name: Install Flex and Bison
      run: sudo apt-get update && sudo apt-get install bison flex libfl-dev

    - name: Build p4c
      run: bazel build //... --verbose_failures --distinct_host_configuration=false

  build_indirect:  # Build 3rd party Bazel project depending on p4c as a subproject.
    runs-on: ubuntu-latest
    env:
      BAZEL: bazelisk-linux-amd64
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: "~/.cache/bazel"
        # Create cash entry for every run (by using unique key derived from commit hash).
        # See https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
        key: ${{ runner.os }}-${{ env.CACHE_ID }}-bazel-build-indirect
        restore-keys: |
          ${{ runner.os }}-${{ env.CACHE_ID }}-bazel-build-indirect

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/$BAZEL"
        chmod +x $BAZEL
        sudo mv $BAZEL /usr/local/bin/bazel

    - name: Install Flex and Bison
      run: sudo apt-get update && sudo apt-get install bison flex libfl-dev

    - name: Build bazel/example
      run: cd ./bazel/example && bazel build //... --verbose_failures --distinct_host_configuration=false
