name: "test-tools"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # The CACHE_ID is 1 if the run happens on the main branch or the pull request was newly opened.
  # Otherwise, the ID corresponds to the pull request ID.
  # We have to use this boolean syntax because Github actions do not support ternary expressions.
  CACHE_ID: ${{ github.event_name == 'pull_request' && (github.event.action != 'opened' && github.event.pull_request.number || '' ) || ''}}

# Cancel any preceding run on the pull request.
concurrency:
  group: p4tools-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # Build and test p4tools on Ubuntu 20.04.
  build-and-test-tools:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    env:
      CTEST_PARALLEL_LEVEL: 4
      IMAGE_TYPE: test
      ENABLE_UNIFIED_COMPILATION: ON
      ENABLE_TEST_TOOLS: ON
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: test-tools-${{ runner.os }}-${{ env.CACHE_ID }}
        max-size: 1000M
        append-timestamp: false

    - name: Build (Ubuntu 20.04)
      run: |
        tools/ci-build.sh

    - name: Run tests (Ubuntu 20.04)
      # Need to use sudo for the eBPF kernel tests.
      run: sudo -E ctest -R testgen- --output-on-failure --schedule-random
      working-directory: ./build
