name: "static-build-test-p4c"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # The CACHE_ID is 1 if the run happens on the main branch or the pull request was newly opened.
  # Otherwise, the ID corresponds to the pull request ID.
  # We have to use this boolean syntax because Github actions do not support ternary expressions.
  CACHE_ID: ${{ github.event_name == 'pull_request' && (github.event.action != 'opened' && github.event.pull_request.number || '' ) || ''}}

# Cancel any preceding run on the pull request.
concurrency:
  group: static-build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # Build a p4c release on Ubuntu 20.04.
  build-linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    env:
      IMAGE_TYPE: test
      ENABLE_UNIFIED_COMPILATION: ON
      BUILD_STATIC_RELEASE: ON
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: test-static-${{ runner.os }}-${{ env.CACHE_ID }}
        max-size: 1000M
        append-timestamp: false

    - name: Build (Ubuntu 20.04)
      run: |
        sudo -E tools/ci-build.sh
