name: "validate-p4c"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # The CACHE_ID is 1 if the run happens on the main branch or the pull request was newly opened.
  # Otherwise, the ID corresponds to the pull request ID.
  # We have to use this boolean syntax because Github actions do not support ternary expressions.
  CACHE_ID: ${{ github.event_name == 'pull_request' && (github.event.action != 'opened' && github.event.pull_request.number) && '' }}

# Cancel any preceding run on the pull request.
concurrency:
  group: validation-${{ env.CACHE_ID }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # We run validation in parallel with the normal tests.
  # Validation ensures that P4C compiles P4-16 programs correctly.
  # We only test the front end and some mid end passes for now.
  validate:
    env:
      CTEST_PARALLEL_LEVEL: 4
      IMAGE_TYPE: test
      ENABLE_UNIFIED_COMPILATION: ON
      VALIDATION: ON
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: validation-${{ runner.os }}-${{ env.CACHE_ID }}
        max-size: 1000M
        append-timestamp: false

    - name: Build (Ubuntu 20.04)
      run: |
        tools/ci-build.sh

    - name: Validate
      run: ctest -R toz3-validate-p4c --output-on-failure --schedule-random
      working-directory: ./build
